export const planets = {
  FETCH_PLANET_DETAILS_REQUEST: 'FETCH_PLANET_DETAILS_REQUEST',
  FETCH_PLANET_DETAILS_SUCCESS: 'FETCH_PLANET_DETAILS_SUCCESS',
  FETCH_PLANET_DETAILS_FAILED:'FETCH_PLANET_DETAILS_FAILED',
};
